FROM node:latest

LABEL author=varga_marton@4dsoft.hu

WORKDIR /workspace

COPY ./package.json ./package.json
COPY ./src ./src
COPY *.json ./

RUN npm i -g @nestjs/cli && npm install && nest build

EXPOSE 3000

CMD node ./dist/main
